apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'kubernetes'
        static_configs:
          - targets:
              - user-service:80
              - inventory-service:80
              - order-service:80
              - payment-service:80
              - notification-service:80