apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      serviceAccountName: sns-sa
      containers:
        - name: notification-service
          image: nexus.ascloud.space/notification-service:8
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: redpanda:9092
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: notification-service
            - name: SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET
              value: earliest

            - name: AWS_REGION
              value: ap-south-1
            - name: AWS_SNS_TOPIC_ARN
              value: arn:aws:sns:ap-south-1:463423328685:sneakhive-invoice-topic
