apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: nexus.ascloud.space/payment-service:5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: redpanda:9092
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: payment-service
            - name: SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET
              value: earliest