apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inventory-service
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/Akhilsabbisetty/gitops-repo.git
    path: base/inventory
  destination:
    server: https://kubernetes.default.svc
    namespace: default